INSERT INTO questions (quiz_id, question, correct_answer, option_1, option_2, option_3, option_4)
VALUES (1, 'What is the capital city of Canada', 'Ottawa', 'Toronto' , 'Calgary' , 'Montreal', 'Ottawa'),
(1, 'What is Koji favorite fruit', 'orange', 'apple', 'peach', 'orange', 'pear'),
(2, 'what is Harsh favorite animal', 'bird', 'dog', 'cat', 'bird', 'gorilla'),
(2, 'What is Isaac favorite sport', 'basketball', 'baseball', 'soccer', 'basketball', 'hockey'),
(2, 'What is Harsh favorite fruit', 'orange', 'apple', 'peach', 'orange', 'pear'),
(2, 'What is Koji favorite sport', 'soccer', 'baseball', 'soccer', 'basketball', 'hockey'),
(2, 'What is Harsh favorite sport', 'hockey', 'baseball', 'soccer', 'basketball', 'hockey'),
(3, 'what is Koji favorite animal', 'bird', 'dog', 'cat', 'bird', 'gorilla'),
(3, 'What is Isaacs favorite fruit', 'peach', 'apple', 'peach', 'orange', 'pear'),
(3, 'What is Diegos favorite fruit', 'pear', 'apple', 'peach', 'orange', 'pear'),
(4, 'What is Diegos favorite sport', 'baseball', 'baseball', 'soccer', 'basketball', 'hockey'),
(4, 'what is Harsh favorite animal', 'bird', 'dog', 'cat', 'bird', 'gorilla'),
(4, 'what is Maria favorite animal', 'bird', 'dog', 'cat', 'bird', 'gorilla'),
(4, 'what is John favorite animal', 'bird', 'dog', 'cat', 'bird', 'gorilla'),
(5, 'What is Issac favorite fruit', 'orange', 'apple', 'peach', 'orange', 'pear');
