INSERT INTO answered_questions (question_id, given_answer)
VAlUES (1, 'Ottawa'),
(2, 'bird'),
(3, 'peach'),
(4, 'apple'),
(5, 'Jupiter'),
(6, 'orange'),
(7, 'Mars'),
(8, 'Australia'),
(9, 'outside'),
(10, 'soccer'),
(11, 'hockey'),
(12, 'star'),
(13, 'dog'),
(14, 'piano'),
(15, 'guitar');
